export const INGREDIENT_ADD = "INGREDIENT_ADD";
export const INGREDIENT_REMOVE = "INGREDIENT_REMOVE";
export const BUN_ADD = "BUN_ADD";
export const BUN_REMOVE = "BUN_REMOVE";
export const INGREDIENTS_SET = "INGREDIENTS_SET";
export const INGREDIENTS_RESET = "INGREDIENTS_RESET";

export enum RECIPE_ACTIONS {
  INGREDIENT_ADD,
  INGREDIENT_REMOVE,
  BUN_ADD,
  BUN_REMOVE,
  INGREDIENTS_SET,
  INGREDIENTS_RESET,
}
